# Generated by Django 5.0.1 on 2026-01-20 01:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('dba_name', models.CharField(blank=True, max_length=200, verbose_name='DBA Name')),
                ('ein', models.CharField(blank=True, max_length=20, verbose_name='EIN')),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('tax_filing_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('physical_address', models.TextField(blank=True)),
                ('physical_city', models.CharField(blank=True, max_length=100)),
                ('physical_state', models.CharField(blank=True, max_length=2)),
                ('physical_zip', models.CharField(blank=True, max_length=10)),
                ('mailing_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('manager_phone', models.CharField(blank=True, max_length=20)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('sos_number', models.CharField(blank=True, max_length=50, verbose_name='SOS Number')),
                ('sos_state', models.CharField(blank=True, max_length=2, verbose_name='SOS State')),
                ('sos_renewal_date', models.DateField(blank=True, null=True, verbose_name='SOS Renewal Date')),
                ('partnership_splits', models.TextField(blank=True)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'ordering': ['entity_code'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Sales Tax', 'Sales Tax'), ('Utility', 'Utility'), ('Insurance', 'Insurance'), ('License', 'License'), ('Payroll', 'Payroll'), ('Tax Filing', 'Tax Filing'), ('Loan Payment', 'Loan Payment'), ('Rent/Lease', 'Rent/Lease'), ('Subscription', 'Subscription'), ('Compliance', 'Compliance'), ('Other', 'Other')], max_length=50)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual'), ('One-Time', 'One-Time')], max_length=20)),
                ('next_due', models.DateField()),
                ('due_day', models.IntegerField(blank=True, help_text='Day of month for recurring deadlines', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('remind_days_before', models.IntegerField(default=7, help_text='Days before due date to send reminder', validators=[django.core.validators.MinValueValidator(0)])),
                ('autopay', models.BooleanField(default=False)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Autopay', 'Autopay'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='deadlines.entity')),
            ],
            options={
                'ordering': ['next_due', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('last4', models.CharField(help_text='Last 4 digits', max_length=4)),
                ('network', models.CharField(blank=True, help_text='Visa, Mastercard, Amex, etc.', max_length=50)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='deadlines.entity')),
            ],
            options={
                'ordering': ['entity', 'card_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('Vendor', 'Vendor'), ('Service Provider', 'Service Provider'), ('Customer', 'Customer'), ('Partner', 'Partner'), ('Employee', 'Employee'), ('Contractor', 'Contractor'), ('Other', 'Other')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='deadlines.entity')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('account_number_last4', models.CharField(help_text='Last 4 digits only', max_length=4)),
                ('routing_number', models.CharField(blank=True, max_length=9)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='deadlines.entity')),
            ],
            options={
                'ordering': ['entity', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=100)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='deadlines.entity')),
            ],
            options={
                'verbose_name_plural': 'Insurance Policies',
                'ordering': ['entity', 'policy_type'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('renewal_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='deadlines.entity')),
            ],
            options={
                'ordering': ['entity', 'license_type'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100)),
                ('lender', models.CharField(max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_frequency', models.CharField(blank=True, max_length=20)),
                ('origination_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='deadlines.entity')),
            ],
            options={
                'ordering': ['entity', 'loan_type'],
            },
        ),
    ]
