# Generated by Django 5.2.3 on 2026-01-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(help_text='e.g., Square, Toast, AccessOne', max_length=100)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('terminal_id', models.CharField(blank=True, max_length=100)),
                ('portal_url', models.URLField(blank=True)),
                ('dba_name', models.CharField(blank=True, max_length=200, verbose_name='DBA Name on Processor')),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_processors', to='deadlines.entity')),
            ],
            options={
                'verbose_name': 'Merchant Processor',
                'verbose_name_plural': 'Merchant Processors',
                'ordering': ['entity', 'processor_name'],
            },
        ),
        migrations.CreateModel(
            name='StateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='State abbreviation (e.g., OR, CO)', max_length=2)),
                ('account_type', models.CharField(choices=[('Unemployment Insurance', 'Unemployment Insurance'), ('Sales Tax', 'Sales Tax'), ('Revenue Online', 'Revenue Online'), ('Withholding Tax', 'Withholding Tax'), ('Other', 'Other')], max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('portal_name', models.CharField(blank=True, help_text='e.g., MYUI, Revenue Online', max_length=100)),
                ('portal_url', models.URLField(blank=True)),
                ('login_email', models.EmailField(blank=True, help_text='Login email (not password)', max_length=254)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_accounts', to='deadlines.entity')),
            ],
            options={
                'verbose_name': 'State Account',
                'verbose_name_plural': 'State Accounts',
                'ordering': ['entity', 'state', 'account_type'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('service_location', models.TextField(blank=True, help_text='Address where service is provided')),
                ('purpose', models.CharField(blank=True, help_text='What this vendor provides', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='deadlines.entity')),
            ],
            options={
                'ordering': ['entity', 'vendor_name'],
            },
        ),
    ]
