# Generated by Django 5.2.3 on 2026-01-27 12:56

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_merchantprocessor_stateaccount_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='full_account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Full account number (encrypted)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ssn',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='SSN: XXX-XX-XXXX (encrypted)'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='cvv',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='CVV (encrypted)'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiration',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='MM/YYYY (encrypted)'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='full_card_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Full card number (encrypted)'),
        ),
    ]
