# Generated by Django 5.2.3 on 2026-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0003_bankaccount_full_account_number_contact_ssn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='merchantprocessor',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='stateaccount',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
