# Generated by Django 5.2.3 on 2026-01-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0004_increase_status_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Autopay', 'Autopay'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='business_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entity',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
