# Generated by Django 5.2.3 on 2026-01-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0005_increase_phone_field_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('contract', 'Contract'), ('tax_form', 'Tax Form'), ('receipt', 'Receipt'), ('statement', 'Statement'), ('correspondence', 'Correspondence'), ('license', 'License'), ('insurance', 'Insurance'), ('report', 'Report'), ('notice', 'Notice'), ('other', 'Other')], default='other', max_length=50)),
                ('file_path', models.CharField(blank=True, help_text='Path to file in OneDrive SSOT', max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(db_index=True, help_text='SHA256 hash of file content', max_length=64, unique=True)),
                ('source', models.CharField(choices=[('email', 'Email Attachment'), ('upload', 'Manual Upload'), ('scan', 'Scanned Document')], default='email', max_length=20)),
                ('email_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_from', models.CharField(blank=True, max_length=255)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, help_text='Date on the document itself', null=True)),
                ('due_date', models.DateField(blank=True, help_text='If document has a due date (invoice, etc.)', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='deadlines.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('payment', 'Payment'), ('review', 'Review'), ('respond', 'Respond'), ('verify', 'Verify'), ('schedule', 'Schedule'), ('renew', 'Renew/Cancel Decision'), ('file', 'File/Organize'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('email', 'Email'), ('manual', 'Manual'), ('deadline', 'Deadline'), ('document', 'Document')], default='email', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('email_id', models.CharField(blank=True, db_index=True, help_text='Gmail message ID for deduplication', max_length=255)),
                ('email_thread_id', models.CharField(blank=True, max_length=255)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_from', models.CharField(blank=True, max_length=255)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible storage for source-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='deadlines.deadline')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='deadlines.document')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='deadlines.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['sha256_hash'], name='deadlines_d_sha256__1758f6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['email_id'], name='deadlines_d_email_i_d05d59_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity', 'document_type'], name='deadlines_d_entity__cec643_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['email_id'], name='deadlines_t_email_i_5ed32a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='deadlines_t_status_19b292_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['entity', 'status'], name='deadlines_t_entity__a677a1_idx'),
        ),
    ]
